import LoginForm from '@/components/login-form';
import { database } from '@/db/raw';
import { safeNext,digest } from '@/lib/auth';
export const dynamic='force-dynamic';
export default async function LoginPage({searchParams}:{searchParams:Promise<{next?:string;error?:string;invite?:string}>}){
 const {next,error,invite}=await searchParams;
 let setup=false,inviteError=false,unavailable=false;
 if(invite){try{setup=/^[a-f0-9]{64}$/.test(invite)&&!!await database().prepare('SELECT token_hash FROM invitations WHERE token_hash=? AND used_by IS NULL AND expires_at>?').bind(await digest(invite),Date.now()).first();inviteError=!setup;}catch{unavailable=true;}}
 const messages:Record<string,string>={origin:'Please open the app directly and try again.',fields:'Check your username and password. Use a password with 12–128 characters.',attempts:'Too many login attempts. Please try again in 15 minutes.',exists:'That username is already taken. Choose another.',credentials:'Incorrect username or password.',unavailable:'Login is temporarily unavailable. Please try again.',confirm:'The passwords do not match.',invite:'This invitation has expired or was already used. Ask the owner for a new link.',registration:'The username or invitation is no longer available. Try another username or ask for a new invitation.'};
 return <main className="login-page"><div className="login-brand"><img className="brand-logo" src="/hyvision-logo.png" alt="HyVISION logo"/><span className="site-brand-name">HVS<span className="brand-sub">Program Management System</span></span></div><section className="login-card"><div className="eyebrow">HyVISION SYSTEM PROGRAM MANAGEMENT</div><h1>{setup?'Create your account':'Welcome back'}<span className="title-dot">.</span></h1><p className="login-intro">{setup?'Choose your own username and password to join the shared project workspace.':'Log in to your project workspace.'}</p>{unavailable?<div className="error" role="alert">Login is temporarily unavailable. Please reload this page.</div>:<>{inviteError&&<div className="error" role="alert">This invitation has expired or was already used. Ask the owner for a new link, or sign in with your existing account.</div>}<LoginForm setup={setup} invite={setup?invite:undefined} next={safeNext(next||null)} serverError={messages[error||'']}/></>}<div className="login-note">{setup?'Invitation registration · HyVISION SYSTEM':'New here? Ask the owner for an invitation link.'}</div></section><div className="login-footer">HVS Program Management System</div></main>;
}
