 'use client';
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,X} from 'lucide-react';
import {requestJSON} from '@/lib/client-api';
import {plainText} from '@/lib/content';
import RichEditor from './rich-editor';
import RichContent from './rich-content';
type Message={id:string;author:string;content:string;createdAt:number};
export default function ChatButton({projectId,projectName}:{projectId:string;projectName:string}){
 const dialog=useRef<HTMLDialogElement>(null),[opened,setOpened]=useState(false),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[draftKey,setDraftKey]=useState(0),[error,setError]=useState(''),[sending,setSending]=useState(false),[allowed,setAllowed]=useState(false),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false);const messageId=useRef(crypto.randomUUID());
 async function load(){try{const m=await requestJSON<Message[]>('/api/chat?projectId='+encodeURIComponent(projectId));setMessages(m);setAllowed(true);setError('');}catch(e){setAllowed(false);setError(e instanceof Error?e.message:'Could not load chat.');}finally{setLoading(false);}}
 useEffect(()=>{if(!opened)return;setLoading(true);load();const poll=setInterval(()=>{if(document.visibilityState==='visible')load();},5000);return()=>clearInterval(poll);},[opened,projectId]);
 async function send(){setSending(true);setError('');try{await requestJSON('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,content:draft,id:messageId.current})});messageId.current=crypto.randomUUID();setDraft('');setDraftKey(k=>k+1);await load();}catch(e){setError(e instanceof Error?e.message:'Could not send message.');}finally{setSending(false);}}
 return <><button className="secondary small-button" onClick={()=>{setOpened(true);dialog.current?.showModal();}}><MessageCircle size={16}/> Chatroom</button><dialog className="chat-dialog" ref={dialog} onCancel={e=>{if(sending||uploading)e.preventDefault();else setOpened(false);}}><div className="dialog-header"><div><h2>{projectName} · Chatroom</h2><p>Linked roster members only</p></div><button className="icon-button" aria-label="Close chat" disabled={sending||uploading} onClick={()=>{dialog.current?.close();setOpened(false);}}><X/></button></div><div className="form-body">{error&&<div className="error" role="alert">{error}<button onClick={load}>Retry</button></div>}<div className="chat-messages" aria-live="polite">{loading?<p>Loading chat…</p>:!messages.length&&allowed?<p className="muted">Start the project conversation.</p>:messages.map(m=><article className="chat-message" key={m.id}><div><strong>{m.author}</strong><time>{new Date(m.createdAt).toLocaleString()}</time></div><RichContent content={m.content}/></article>)}</div>{allowed&&<><RichEditor key={draftKey} value={draft} onChange={setDraft} scope="chat" resourceId={projectId} disabled={sending} onUploading={setUploading}/><div className="dialog-footer"><button className="primary" disabled={sending||uploading||!plainText(draft).trim()||draft.length>20000} onClick={send}>{sending?'Sending…':'Send message'}</button></div></>}</div></dialog></>;
}
