'use client';
import RiskBadge,{projectRisk} from './risk-badge';
import {useAccess} from './access-context';
import { useState } from 'react';
import { Plus } from 'lucide-react';
import type { Project } from '@/lib/project';
import type { Customer } from '@/lib/customer';
import { customerKey,customerRows,formatDay,localDay,scheduleLabel,statusClass } from '@/lib/dashboard-view';

export default function DashboardOverview({projects,customers,unavailable}:{projects:Project[];customers:Customer[];unavailable:boolean}){
 const access=useAccess();
 const [activeOnly,setActiveOnly]=useState(true),[customer,setCustomer]=useState('');
 const today=localDay(),directory=customerRows(projects,customers);
 const tasks=projects.flatMap(p=>p.actions.filter(a=>!a.done).map(a=>({...a,project:p}))).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));
 const attention=tasks.filter(t=>(t.due&&t.due<=today)||t.risk==='High'||t.risk==='Critical').length;
 const visibleProjects=projects.filter(p=>(!activeOnly||p.status!=='Completed')&&(!customer||customerKey(p.customer)===customer));
 return <div className="content overview"><div className="page-heading"><div><h1>Dashboard</h1><p>Your projects, tasks, and customer relationships.</p></div>{access.canEdit&&<a target="_self" className="primary" href="/projects"><Plus size={17}/> Create project</a>}</div>{unavailable&&<div className="error" role="alert">Dashboard data could not be loaded. <a href="/dashboard" target="_self">Reload dashboard</a></div>}
 <section className="overview-section" aria-labelledby="overview-tasks"><div className="section-title"><div><h2 id="overview-tasks"><a href="/tasks" target="_self">My Tasks</a></h2><span>{unavailable?'—':tasks.length} open tasks</span>{attention>0&&<span className="attention-badge">{attention} need attention</span>}</div><a className="section-link" href="/tasks" target="_self">{access.canEdit?'View / edit tasks':'View tasks'}</a></div><div className="panel">{tasks.length?<div className="table-scroll"><table className="overview-table"><thead><tr><th scope="col">Task</th><th scope="col">Project</th><th scope="col">Owner</th><th scope="col">Risk</th><th scope="col">Schedule</th><th scope="col">Progress</th><th scope="col">Status</th></tr></thead><tbody>{tasks.slice(0,8).map(t=><tr key={t.project.id+':'+t.id} className={(t.due&&t.due<=today)||t.risk==='High'||t.risk==='Critical'?'attention-row':''}><td><a className="task-name" href="/tasks" target="_self">{t.title}</a></td><td><a className="row-identity" href={'/projects/'+t.project.id} target="_self"><span className="company-monogram">{t.project.customer.slice(0,2).toUpperCase()}</span><span>{t.project.name}<small>{t.project.customer}</small></span></a></td><td>{t.owner||'Unassigned'}</td><td><RiskBadge risk={t.risk}/></td><td><span className={'schedule-label '+(t.due&&t.due<=today?'attention':'')}>{scheduleLabel(t.due,t.done,today)}</span><span className="customer">{formatDay(t.due)}</span></td><td><div className="task-progress"><div role="progressbar" aria-label={t.title+' progress'} aria-valuenow={t.progress||0} aria-valuemin={0} aria-valuemax={100}><span style={{width:(t.progress||0)+'%'}}/></div><span>{t.progress||0}%</span></div></td><td><span className={'badge '+(t.progress?'production':'planning')}>{t.progress?'In progress':'Assigned'}</span></td></tr>)}</tbody></table></div>:<div className="overview-empty">{unavailable?'Task summary unavailable.':<>No open tasks. <a href="/tasks" target="_self">Open My Tasks</a> to add your next steps.</>}</div>}{tasks.length>8&&<a className="show-all" href="/tasks" target="_self">View all {tasks.length} open tasks</a>}</div></section>
 <section className="overview-section" aria-labelledby="overview-projects"><div className="section-title"><div><h2 id="overview-projects"><a href="/projects" target="_self">My Projects</a></h2><span>{unavailable?'—':visibleProjects.length} projects</span></div><a className="section-link" href="/projects" target="_self">{access.canEdit?'View / edit projects':'View projects'}</a></div><div className="overview-filters"><label><input type="checkbox" checked={activeOnly} onChange={e=>setActiveOnly(e.target.checked)}/> Active only</label><label className="customer-filter"><span className="sr-only">Filter projects by customer</span><select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">All customers</option>{directory.map(c=><option key={customerKey(c.name)} value={customerKey(c.name)}>{c.name}</option>)}</select></label></div><div className="panel">{visibleProjects.length?<div className="table-scroll"><table className="overview-table"><thead><tr><th scope="col">Customer / Project</th><th scope="col">Phase</th><th scope="col">PM</th><th scope="col">RFQ received</th><th scope="col">Open tasks</th><th scope="col">Risk</th><th scope="col">Schedule</th></tr></thead><tbody>{visibleProjects.map(p=>{const actions=p.actions.filter(a=>!a.done),late=actions.filter(a=>a.due&&a.due<today).length,next=actions.filter(a=>a.due).sort((a,b)=>a.due.localeCompare(b.due))[0];return <tr key={p.id}><td><a className="row-identity" href={'/projects/'+p.id} target="_self"><span className="company-monogram">{p.customer.slice(0,2).toUpperCase()}</span><span><strong>{p.name}</strong><small>{p.customer}</small></span></a></td><td><span className={'badge '+statusClass(p.status)}>{p.status}</span></td><td>{p.team.pm||'Unassigned'}</td><td>{formatDay(p.dates.rfq)}</td><td>{actions.length}</td><td><RiskBadge risk={projectRisk(actions)}/></td><td><span className={'schedule-label '+(late?'attention':'')}>{p.status==='Completed'?'Completed':late?late+' overdue':next?'Next task due':'Not scheduled'}</span>{next&&<span className="customer">{formatDay(next.due)}</span>}</td></tr>})}</tbody></table></div>:<div className="overview-empty">{unavailable?'Project summary unavailable.':projects.length?'No projects match these filters.':<>No projects yet. <a href="/projects" target="_self">Create your first project.</a></>}</div>}</div></section>
 {access.role!=='customer'&&<section className="overview-section" aria-labelledby="overview-customers"><div className="section-title"><div><h2 id="overview-customers"><a href="/customers" target="_self">Customers</a></h2><span>{unavailable?'—':directory.length} customers</span></div><a className="section-link" href="/customers" target="_self">View / add customers</a></div><div className="panel">{directory.length?<div className="table-scroll"><table className="overview-table"><thead><tr><th scope="col">Customer</th><th scope="col">Projects</th><th scope="col">Meeting minutes</th><th scope="col">Contacts</th><th scope="col">Latest meeting</th></tr></thead><tbody>{directory.map(c=><tr key={customerKey(c.name)}><td><a className="row-identity" href={c.customer?'/customers/'+c.customer.id:'/customers'} target="_self"><span className="company-monogram">{c.name.slice(0,2).toUpperCase()}</span><strong>{c.name}</strong></a></td><td>{c.projects||<span className="muted">No project</span>}</td><td>{c.customer?.minutes.length||<span className="muted">No record</span>}</td><td>{c.customer?.contacts.length||<span className="muted">No contacts</span>}</td><td>{formatDay(c.latestMeeting)}</td></tr>)}</tbody></table></div>:<div className="overview-empty">{unavailable?'Customer summary unavailable.':<>No customers yet. <a href="/customers" target="_self">Add a customer.</a></>}</div>}</div></section>}<footer>HVS Program Management System<span>HyVISION SYSTEM · US</span></footer></div>;
}
