'use client';
import { useEffect,useState } from 'react';
import { Eye,EyeOff,LockKeyhole } from 'lucide-react';
export default function LoginForm({setup,next,serverError,invite}:{setup:boolean;next:string;serverError?:string;invite?:string}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [embedded,setEmbedded]=useState(false);
 useEffect(()=>{setEmbedded(window.self!==window.top);const reset=()=>setBusy(false);window.addEventListener('pageshow',reset);return()=>window.removeEventListener('pageshow',reset);},[]);
 useEffect(()=>{if(!busy)return;const timer=setTimeout(()=>{setBusy(false);setError('Login has not completed. Please try again, or open the app in a new tab.');},12000);return()=>clearTimeout(timer);},[busy]);
 function submit(e:React.FormEvent){setError('');if(setup&&password!==confirm){e.preventDefault();setError('The passwords do not match.');return;}setBusy(true);}
 return <form className="login-form" action="/login" method="post" target="_self" onSubmit={submit}><input type="hidden" name="setup" value={String(setup)}/><input type="hidden" name="next" value={next}/>{invite&&<input type="hidden" name="invite" value={invite}/>}<label htmlFor="username">Enter Username<input id="username" name="username" required autoFocus autoComplete="username" minLength={3} maxLength={60} pattern="[a-zA-Z0-9_.@\-]+" placeholder={setup?'Choose a username':'Enter your username'} value={username} onChange={e=>setUsername(e.target.value)}/></label><label htmlFor="password">Password<div className="password-field"><input id="password" name="password" required minLength={12} maxLength={128} autoComplete={setup?'new-password':'current-password'} type={visible?'text':'password'} placeholder={setup?'Choose a password':'Enter your password'} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" aria-label={visible?'Hide password':'Show password'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{setup&&<><p className="password-hint">Passwords need at least 12 characters.</p><label htmlFor="confirm">Confirm password<input id="confirm" name="confirm" required type={visible?'text':'password'} autoComplete="new-password" minLength={12} maxLength={128} placeholder="Enter your password again" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>}{(error||serverError)&&<div className="error" role="alert">{error||serverError}</div>}<button type="submit" className="primary login-submit" disabled={busy}><LockKeyhole size={17}/>{busy?(setup?'Creating login…':'Logging in…'):setup?'Create account & open dashboard':'Log in'}</button>{embedded&&<a className="login-open-direct" href="/" target="_blank" rel="noopener noreferrer">Open app in a new tab</a>}</form>;
}
