'use client';
import {useRef,useState} from 'react';
import {ChevronDown,ChevronRight,Plus,Check} from 'lucide-react';
import RiskBadge,{projectRisk} from './risk-badge';
import DependencyLines from '@/components/dependency-lines';
import {waitingForPredecessor,taskWbs} from '@/lib/task-dependencies';
import type {Project} from '@/lib/project';
import {dayNumber,isoDay,timelineRange,barPosition} from '@/lib/task-timeline';
type Action=Project['actions'][number];
type Milestone=Project['milestones'][number];
type BoardProject=Pick<Project,'id'|'name'|'customer'|'milestones'|'actions'>;
export default function MilestoneBoard({project,filter='all',busy=false,rosterControl,onAdd,onEdit,onToggle,onMilestone}:{project:BoardProject;filter?:'all'|'open'|'completed';busy?:boolean;rosterControl?:React.ReactNode;onAdd?:(id:string)=>void;onEdit?:(a:Action)=>void;onToggle?:(a:Action)=>void;onMilestone?:(m:Milestone)=>void}){
 const grid=useRef<HTMLDivElement>(null),wbs=taskWbs(project);
 const [collapsed,setCollapsed]=useState<string[]>([]);
 const groups=[...(project.milestones||[]).map(m=>({...m,tasks:project.actions.filter(a=>a.milestoneId===m.id)})),{id:'',title:'Unassigned tasks',category:'Custom' as const,start:'',due:'',tasks:project.actions.filter(a=>!a.milestoneId)}].filter(g=>g.id||g.tasks.length);
 const scheduled=[...project.actions,...(project.milestones||[])].filter(a=>a.start||a.due).map(a=>({start:a.start||a.due,due:a.due||a.start}));
 const original=timelineRange(scheduled),range=original?{first:original.first-2,last:original.last+2,days:original.days+4}:null,today=dayNumber(new Date().toISOString().slice(0,10));
 const months:{label:string;left:number;width:number}[]=[];
 if(range){let day=range.first;while(day<=range.last){const date=new Date(isoDay(day)+'T00:00:00Z');const next=Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,1)/86400000;const end=Math.min(next,range.last+1);months.push({label:date.toLocaleDateString('en-US',{month:'short',year:'numeric',timeZone:'UTC'}),left:100*(day-range.first)/range.days,width:100*(end-day)/range.days});day=end;}}
 function timeline(start:string,due:string,progress:number,summary=false,title='',taskId=''){
  const position=range&&(start||due)?barPosition(start||due,due||start,range):null;
  return <div className="milestone-timeline">{months.map(m=><span key={m.left} className="timeline-gridline" style={{left:m.left+'%'}}/>)}{range&&today>=range.first&&today<=range.last&&<span className="timeline-today" style={{left:100*(today-range.first)/range.days+'%'}}/>}{position?<div data-task-bar={taskId||undefined} title={`${title}: ${start||due} – ${due||start} · ${progress}%`} className={'milestone-bar '+(summary?'summary-bar':'')} style={{left:position.left+'%',width:position.width+'%'}}><span style={{width:progress+'%'}}/><b>{progress}%</b></div>:<span className="timeline-unscheduled">Not scheduled</span>}</div>;
 }
 return <section className="panel milestone-project"><div className="panel-heading"><div><h2>{project.name}</h2><span className="muted">{project.customer} · {project.actions.length} tasks</span></div><div className="page-controls">{rosterControl}{onAdd&&<button className="secondary small-button" disabled={busy} onClick={()=>onAdd('')}><Plus size={14}/> Add task</button>}</div></div><div className="table-scroll"><div ref={grid} className="milestone-grid" role="table" aria-label={project.name+' milestones and task timeline'}><div className="milestone-row milestone-column-head" role="row"><span>No.</span><span>MILESTONES & TASKS</span><span>OWNER</span><span>RISK</span><span>START</span><span>DUE</span><span>PROGRESS</span><div className="milestone-months">{months.length?months.map(m=><span key={m.left} style={{left:m.left+'%',width:m.width+'%'}}>{m.label}</span>):<span>Task timeline</span>}</div></div>{groups.map((g,index)=>{
 const shown=g.tasks.filter(a=>filter==='all'||(filter==='completed'?a.done:!a.done));
 const starts=g.tasks.flatMap(a=>a.start?[a.start]:a.due?[a.due]:[]),ends=g.tasks.flatMap(a=>a.due?[a.due]:a.start?[a.start]:[]);
 const start=[...starts,...(g.start?[g.start]:[]),...(g.due?[g.due]:[])].sort()[0]||'',due=[...ends,...(g.due?[g.due]:[]),...(g.start?[g.start]:[])].sort().at(-1)||'';
 const progress=g.tasks.length?Math.round(g.tasks.reduce((n,a)=>n+(a.done?100:a.progress||0),0)/g.tasks.length):0;
 const closed=collapsed.includes(g.id);
 return <div key={g.id}><div className="milestone-row milestone-parent" role="row"><span className="wbs">{index+1}</span><div className="milestone-name"><button className="icon-button" aria-label={(closed?'Expand ':'Collapse ')+g.title} aria-expanded={!closed} onClick={()=>setCollapsed(v=>closed?v.filter(id=>id!==g.id):[...v,g.id])}>{closed?<ChevronRight size={16}/>:<ChevronDown size={16}/>}</button>{onMilestone&&g.id?<button className="milestone-title" onClick={()=>onMilestone(g)}>{g.title}</button>:<strong>{g.title}</strong>}<small>{g.tasks.length}</small>{onAdd&&<button className="icon-button" disabled={busy} aria-label={'Add task to '+g.title} onClick={()=>onAdd(g.id)}><Plus size={15}/></button>}</div><span>—</span><span><RiskBadge risk={projectRisk(g.tasks)}/></span><span>{start||'—'}</span><span>{due||'—'}</span><span>{progress}%</span>{timeline(start,due,progress,true,g.title)}</div>{!closed&&shown.map(a=><div className="milestone-row milestone-task" role="row" key={a.id}><span className="wbs">{index+1}.{g.tasks.indexOf(a)+1}</span><div className="milestone-name">{onToggle?<button className={'check-button '+(a.done?'checked':'')} disabled={busy} aria-label={(a.done?'Reopen ':'Complete ')+a.title} onClick={()=>onToggle(a)}>{a.done&&<Check size={14}/>}</button>:<span>{a.done?'✓':'○'}</span>}{onEdit?<button className={'milestone-title '+(a.done?'done':'')} onClick={()=>onEdit(a)}>{a.title}</button>:<span className={a.done?'done':''}>{a.title}</span>}{a.predecessorId&&<small className="predecessor-tag" title={'Predecessor: '+(project.actions.find(t=>t.id===a.predecessorId)?.title||'')}>After {wbs.get(a.predecessorId)||'task'}</small>}{!a.done&&waitingForPredecessor(a,project.actions)&&<small className="waiting-tag">Waiting</small>}</div><span>{a.owner||'Unassigned'}</span><span><RiskBadge risk={a.risk}/></span><span>{a.start||'—'}</span><span>{a.due||'—'}</span><span>{a.done?100:a.progress||0}%</span>{timeline(a.start,a.due,a.done?100:a.progress||0,false,a.title,a.id)}</div>)}{!closed&&!shown.length&&<div className="milestone-empty">{g.tasks.length?'No tasks match this filter.':'No tasks yet. Use + to add a task under this milestone.'}</div>}</div>;
 })}{!groups.length&&<div className="milestone-empty">Add a milestone to organize this project’s tasks.</div>}<DependencyLines container={grid} tasks={project.actions} layoutKey={filter+collapsed.join(',')}/></div></div><div className="milestone-legend"><span><i/>Task progress</span><span><i className="legend-summary"/>Milestone rollup</span><span><i className="legend-today"/>Today</span><span><i className="legend-link"/>Predecessor connection</span><span>Click a task or milestone name to edit.</span></div></section>;
}
