 'use client';
import {useEffect,useRef,useState} from 'react';
import {richNodes,richPrefix,type RichNode} from '@/lib/content';
export default function RichEditor({value,onChange,scope,resourceId='',disabled=false,onUploading}:{value:string;onChange:(v:string)=>void;scope:'project'|'chat'|'notes'|'customer';resourceId?:string;disabled?:boolean;onUploading?:(v:boolean)=>void}){
 const editor=useRef<HTMLDivElement>(null),picker=useRef<HTMLInputElement>(null),selection=useRef<Range|null>(null),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const el=editor.current;if(!el)return;el.replaceChildren();for(const n of richNodes(value)){if(n.type==='file'){insertAttachment(n,false);continue;}const span=document.createElement('span');span.textContent=n.text;if(n.bold)span.style.fontWeight='700';if(n.italic)span.style.fontStyle='italic';if(n.underline)span.style.textDecoration='underline';if(n.color)span.style.color=n.color;if(n.size)span.style.fontSize=n.size+'px';el.appendChild(span);} },[]);
 function remember(){const s=window.getSelection();if(s?.rangeCount&&editor.current?.contains(s.anchorNode))selection.current=s.getRangeAt(0).cloneRange();}
 function serialize(){const nodes:RichNode[]=[];function walk(n:Node,marks:Partial<Extract<RichNode,{type:'text'}>>={}){if(n.nodeType===3){nodes.push({type:'text',text:n.textContent||'',...marks});return;}if(!(n instanceof HTMLElement))return;if(n.dataset.file){nodes.push({type:'file',id:n.dataset.file,name:n.dataset.name||'Attachment',image:n.dataset.image==='true'});return;}if(n.tagName==='BR'){nodes.push({type:'text',text:'\n'});return;}const next={...marks};if(n.style.fontWeight==='normal'||n.style.fontWeight==='400')next.bold=false;if(n.style.fontStyle==='normal')next.italic=false;if(n.style.textDecoration==='none')next.underline=false;if(n.tagName==='LI')nodes.push({type:'text',text:'• '});if(['B','STRONG'].includes(n.tagName)||Number(n.style.fontWeight)>=600)next.bold=true;if(['I','EM'].includes(n.tagName)||n.style.fontStyle==='italic')next.italic=true;if(n.tagName==='U'||n.style.textDecoration.includes('underline'))next.underline=true;const color=n.style.color||n.getAttribute('color');if(color){const match=color.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);const hex=match?'#'+match.slice(1).map(v=>Number(v).toString(16).padStart(2,'0')).join(''):color;if(/^#[\da-f]{6}$/i.test(hex))next.color=hex;}const size=n.style.fontSize.replace('px','');if(['14','16','20','24'].includes(size))next.size=size as '16';for(const c of n.childNodes)walk(c,next);if(['DIV','P','LI'].includes(n.tagName))nodes.push({type:'text',text:'\n'});}
 for(const n of editor.current?.childNodes||[])walk(n);onChange(richPrefix+JSON.stringify(nodes));remember();}
 function command(cmd:string,arg?:string){editor.current?.focus();const s=window.getSelection();if(selection.current&&s){s.removeAllRanges();s.addRange(selection.current);}document.execCommand(cmd,false,arg);serialize();}
 function insertAttachment(n:Extract<RichNode,{type:'file'}>,emit=true){const box=document.createElement('span');box.contentEditable='false';box.className='attachment-chip';box.dataset.file=n.id;box.dataset.name=n.name;box.dataset.image=String(n.image);if(n.image){const img=document.createElement('img');img.src='/api/files?id='+n.id;img.alt=n.name;box.appendChild(img);}box.appendChild(document.createTextNode('📎 '+n.name));const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label','Remove '+n.name);remove.onclick=()=>{box.remove();serialize();};box.appendChild(remove);editor.current?.appendChild(box);editor.current?.appendChild(document.createTextNode('\n'));if(emit)serialize();}
 async function upload(files:FileList|File[]){setUploading(true);onUploading?.(true);setError('');try{for(const file of Array.from(files)){const form=new FormData();form.set('file',file);form.set('scope',scope);form.set('resourceId',resourceId);const r=await fetch('/api/files',{method:'POST',body:form});const result=await r.json() as {id:string;name:string;image:boolean;error?:string};if(!r.ok)throw Error(result.error||'Upload failed');insertAttachment({type:'file',...result});}}catch(e){setError(e instanceof Error?e.message:'Upload failed');}finally{setUploading(false);onUploading?.(false);if(picker.current)picker.current.value='';}}
 return <div className={'rich-editor '+(disabled?'disabled':'')}><div className="editor-toolbar" role="toolbar" aria-label="Text formatting"><button type="button" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('bold')} aria-label="Bold"><b>B</b></button><button type="button" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('italic')} aria-label="Italic"><i>I</i></button><button type="button" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('underline')} aria-label="Underline"><u>U</u></button><select disabled={disabled} aria-label="Text size" onChange={e=>{command('fontSize','7');editor.current?.querySelectorAll('font[size="7"]').forEach(n=>{(n as HTMLElement).style.fontSize=e.target.value+'px';n.removeAttribute('size');});serialize();}} defaultValue="16"><option value="14">Small</option><option value="16">Normal</option><option value="20">Heading</option><option value="24">Large</option></select><button type="button" disabled={disabled} onMouseDown={e=>e.preventDefault()} onClick={()=>command('insertUnorderedList')} aria-label="Bullet list">• List</button><input aria-label="Text color" type="color" disabled={disabled} defaultValue="#f3a9ce" onChange={e=>command('foreColor',e.target.value)}/><button type="button" disabled={disabled||uploading} onClick={()=>picker.current?.click()}>📎 {uploading?'Uploading…':'Attach files'}</button><input hidden ref={picker} type="file" multiple onChange={e=>e.target.files&&upload(e.target.files)}/></div><div ref={editor} className="editor-surface" role="textbox" aria-label="Rich text" aria-multiline="true" contentEditable={!disabled&&!uploading} suppressContentEditableWarning onInput={serialize} onKeyUp={remember} onMouseUp={remember} onPaste={e=>{e.preventDefault();if(e.clipboardData.files.length){upload(e.clipboardData.files);return;}command('insertText',e.clipboardData.getData('text/plain'));}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!disabled&&!uploading&&e.dataTransfer.files.length)upload(e.dataTransfer.files);}}/><p className="settings-help">Drop photos or files here · Up to 10 MB per file</p>{error&&<p className="error" role="alert">{error}</p>}</div>;
}
