'use client';
import { CalendarDays } from 'lucide-react';
import type { SharedTask } from '@/lib/shared-view';
import { dayNumber,isoDay,timelineRange,barPosition } from '@/lib/task-timeline';
type Task=SharedTask;
const label=(v:string)=>new Date(v+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export default function TaskGantt<T extends Task>({tasks,onEdit,loading}:{tasks:T[];onEdit?:(task:T)=>void;loading:boolean}){
 const Label=onEdit?'button':'div',Bar=onEdit?'button':'div';
 const scheduled=tasks.filter(t=>t.start&&t.due&&t.start<=t.due),unscheduled=tasks.filter(t=>!t.start||!t.due||t.start>t.due);
 const range=timelineRange(scheduled),now=new Date(),today=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');
 const tickCount=range?Math.min(7,range.days):0;
 const ticks=range?Array.from({length:tickCount},(_,i)=>Math.round(range.first+i*(range.days-1)/Math.max(1,tickCount-1))):[];
 const todayOffset=range?(dayNumber(today)-range.first+.5)*100/range.days:-1;
 return <section className="panel gantt-panel" aria-label="Task Gantt chart"><div className="panel-heading"><div><h2>Task Gantt chart</h2><p>Bars show scheduled duration; the filled portion shows recorded progress.</p></div><div className="gantt-legend"><span><i/> Planned</span><span><i/> Progress</span><span><i/> Today</span></div></div>{loading?<div className="empty compact">Loading timeline…</div>:!range?<div className="empty compact"><CalendarDays size={26}/><h3>No scheduled tasks in this view</h3><p>{onEdit?'Add a start date and due date to show a task on the chart.':'No tasks in this snapshot have both a start date and a due date.'}</p></div>:<><div className="gantt-range-label">{label(isoDay(range.first))} – {label(isoDay(range.last))}</div><div className="gantt-scroll" tabIndex={0} aria-label="Scrollable task timeline"><div className="gantt-grid" style={{minWidth:Math.min(2400,Math.max(960,range.days*20+260))}}><div className="gantt-axis"><div className="gantt-task-label">TASK / PROGRESS</div><div className="gantt-ticks">{ticks.map((d,i)=><span key={d} style={{left:((d-range.first+.5)*100/range.days)+'%',transform:i===0?'none':i===ticks.length-1?'translateX(-100%)':'translateX(-50%)'}}>{new Date(isoDay(d)+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span>)}</div></div>{scheduled.map(t=>{const position=barPosition(t.start,t.due,range),progress=t.done?100:t.progress||0;return <div className="gantt-row" key={t.project.id+':'+t.id}><Label className="gantt-task-label" onClick={onEdit?()=>onEdit(t):undefined}><strong>{t.title}</strong><span>{t.project.name} · {progress}%</span></Label><div className="gantt-track">{ticks.map(d=><i className="gantt-grid-line" key={d} style={{left:((d-range.first+.5)*100/range.days)+'%'}}/>)}{todayOffset>=0&&todayOffset<=100&&<i className="gantt-today" style={{left:todayOffset+'%'}}/>}<Bar className={'gantt-bar '+(t.done?'gantt-completed':'')} style={{left:position.left+'%',width:position.width+'%'}} onClick={onEdit?()=>onEdit(t):undefined} aria-label={`${t.title}: ${label(t.start)} to ${label(t.due)}, ${progress}% complete.${onEdit?' Edit task.':''}`} title={`${t.title}\n${label(t.start)} – ${label(t.due)}\n${progress}% complete`}><span style={{width:progress+'%'}}/></Bar></div></div>;})}</div></div></>}{!loading&&unscheduled.length>0&&<div className="gantt-unscheduled"><h3>Needs scheduling <span className="count">{unscheduled.length}</span></h3>{unscheduled.map(t=><div key={t.project.id+':'+t.id}><span>{t.title}<small>{t.project.name}</small></span><>{onEdit&&<button className="secondary small-button" onClick={()=>onEdit(t)}>Set dates</button>}</></div>)}</div>}</section>;
}
