 'use client';
import {useAccess} from './access-context';
import {useEffect,useRef,useState} from 'react';
import {X,Plus,Pencil} from 'lucide-react';
import {noteSections,type TaskNote} from '@/lib/task-notes';
import {requestJSON} from '@/lib/client-api';
import {plainText} from '@/lib/content';
import RichContent from './rich-content';
import RichEditor from './rich-editor';
type Update={id:string;author:string;content:string;createdAt:number};
export default function TaskNotes(){
 const access=useAccess(),dialog=useRef<HTMLDialogElement>(null),updateId=useRef(crypto.randomUUID());
 const [notes,setNotes]=useState<TaskNote[]>([]),[updates,setUpdates]=useState<Update[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[draft,setDraft]=useState<TaskNote|null>(null),[newUpdate,setNewUpdate]=useState(false),[content,setContent]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[saveError,setSaveError]=useState('');
 async function load(){setLoading(true);setError('');try{const [n,u]=await Promise.all([requestJSON<TaskNote[]>('/api/task-notes'),requestJSON<Update[]>('/api/updates')]);setNotes(n);setUpdates(u);}catch(e){setError(e instanceof Error?e.message:'Could not load notes.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);useEffect(()=>{if(draft||newUpdate)dialog.current?.showModal();else dialog.current?.close();},[!!draft,newUpdate]);
 function edit(note:TaskNote){setSaveError('');setDraft({...note});setContent(note.content);}
 async function save(){setSaving(true);setSaveError('');try{if(newUpdate){const u=await requestJSON<Update>('/api/updates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:updateId.current,content})});setUpdates(old=>[u,...old.filter(x=>x.id!==u.id)]);updateId.current=crypto.randomUUID();setNewUpdate(false);}else if(draft){const n=await requestJSON<TaskNote>('/api/task-notes',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...draft,content})});setNotes(old=>old.map(v=>v.kind===n.kind?n:v));setDraft(null);}}catch(e){setSaveError(e instanceof Error?e.message:'Could not save.');}finally{setSaving(false);}}
 function close(){setDraft(null);setNewUpdate(false);}
 const sections=[noteSections[0],noteSections[2],noteSections[1]],legacy=notes.find(n=>n.kind==='status');
 return <section className="task-notes-section"><h2>Project Summary</h2>{error&&<div className="error" role="alert">{error}<button onClick={load}>Retry</button></div>}<div className="panel summary-stack">{sections.map(([kind,title,prompt])=>{const note=notes.find(n=>n.kind===kind);return <article className="summary-section" key={kind}><div className="panel-heading"><h2>{title}</h2><button className="secondary small-button" disabled={!access.canEdit||loading||!note} onClick={()=>note&&edit(note)}><Pencil size={15}/> {note?.content?'Edit':'Add'}</button></div>{loading?<p>Loading notes…</p>:note?.content?<RichContent content={note.content}/>:<p className="muted">{prompt}</p>}</article>;})}</div><div className="notes-section-heading"><h2>Status Update</h2><span className="muted">Showing updates only · Latest on top</span>{access.canEdit&&<button className="secondary" onClick={()=>{setContent('');setSaveError('');setNewUpdate(true);}}><Plus size={16}/> Add update</button>}</div><div className="update-feed">{updates.map(u=><article className="panel update-card" key={u.id}><div className="panel-heading"><strong>{u.author}</strong><time>{new Date(u.createdAt).toLocaleString()}</time></div><RichContent content={u.content}/></article>)}{legacy?.content&&<article className="panel update-card"><div className="panel-heading"><strong>Previous status update</strong><time>{legacy.updatedAt?new Date(legacy.updatedAt).toLocaleString():''}</time></div><RichContent content={legacy.content}/></article>}{!loading&&!updates.length&&!legacy?.content&&<p className="muted">No updates yet.</p>}</div><dialog ref={dialog} onCancel={e=>{e.preventDefault();if(!saving&&!uploading)close();}}><div className="dialog-header"><h2>{newUpdate?'Add status update':noteSections.find(([k])=>k===draft?.kind)?.[1]}</h2><button className="icon-button" disabled={saving||uploading} aria-label="Close editor" onClick={close}><X/></button></div>{(draft||newUpdate)&&<><div className="form-body"><RichEditor key={newUpdate?'update':draft?.kind} value={content} onChange={setContent} scope="notes" disabled={saving} onUploading={setUploading}/>{saveError&&<div className="error" role="alert">{saveError}</div>}</div><div className="dialog-footer"><button className="secondary" disabled={saving||uploading} onClick={close}>Cancel</button><button className="primary" disabled={saving||uploading||content.length>20000||(newUpdate&&!plainText(content).trim())} onClick={save}>{saving?'Saving…':newUpdate?'Post update':'Save notes'}</button></div></>}</dialog></section>;
}
